# Generated by Django 4.2.7 on 2024-01-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloxfruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightingstyle',
            name='location',
            field=models.CharField(blank=True, choices=[('First Sea', 'First Sea'), ('Second Sea', 'Second Sea'), ('Third Sea', 'Third Sea')], max_length=100, null=True),
        ),
    ]
