# Generated by Django 4.2.7 on 2024-01-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloxfruits', '0002_alter_fightingstyle_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
