# Generated by Django 4.2.7 on 2024-01-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloxfruits', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fightingstyle',
            field=models.ManyToManyField(blank=True, to='bloxfruits.fightingstyle'),
        ),
        migrations.AddField(
            model_name='player',
            name='gun',
            field=models.ManyToManyField(blank=True, to='bloxfruits.gun'),
        ),
        migrations.AddField(
            model_name='player',
            name='sword',
            field=models.ManyToManyField(blank=True, to='bloxfruits.sword'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='bloxfruit',
        ),
        migrations.AddField(
            model_name='player',
            name='bloxfruit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloxfruits.bloxfruit'),
        ),
    ]
