# Generated by Django 4.2.7 on 2024-01-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloxfruits', '0005_player_fightingstyle_player_gun_player_sword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(blank=True, choices=[('Pirate', 'Pirate'), ('Marine', 'Marine')], max_length=100, null=True),
        ),
    ]
